import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const pretendard = localFont({
  src: './fonts/PretendardVariable.woff2',
  display: 'swap',
  variable: '--font-pretendard',
  weight: '45 920',
});

const neurimboGothic = localFont({
  src: './fonts/neurimboGothicRegular.woff',
  display: 'swap',
});

export const metadata: Metadata = {
  title: '사각사각',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${pretendard.variable}`}>
      <body className="font-pretendard">{children}</body>
    </html>
  );
}
